### ISSUE TITLE
no-unused-vars

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#1]
http://eslint.org/docs/rules/no-unused-vars
- vars is set only to local, do we really want global vars in files to go unused?
- args is set to after-used, which means we can’t have unused last parameters

Current

``` javascript
var lib = require('lib');

function ex(a, b) {
  var x = a + 1;
  var z = b + 2;
}
```

Proposed:

``` javascript
    'no-unused-vars': [2, {          // http://eslint.org/docs/rules/no-unused-vars
      'vars': 'all',
      'args': 'none'
    }],
```

Result

``` javascript
function ex(a, b, c) {
  var x = a + 1;
  var z = b + 2;
}
```

**Comment by nzack** [comment]
Use proposed

**Comment by nzack** [comment]
There are more options now in later versions of eslint that support greater configuration of this.  We should revisit this discussion.

**Comment by JasonGhent** [comment]
@conorgil @ravenac95 [your thoughts were here.](https://github.com/virtru/acm/pull/137#discussion_r51011140)

everyone else RFC. @virtru/employees

**Comment by jwvirtru** [comment]
This is set: https://github.com/virtru/lint-trap/blob/master/lib/defaults.js#L67-L70
