### ISSUE TITLE
vars-on-top

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#10]
http://eslint.org/docs/rules/vars-on-top
- Currently required and an error. I really dislike this style. I believe vars should be intelligently declared near their use site, except for module level requires used throughout the file.

Current

``` javascript
function ex(a, b, c) {
  var test, mod2;

  if (a) //do
  if (b) //do

  test = [1,2,3].filter( _ => _ > 1 );
  if (test) //do

  mod2 = test.filter( _ => _ % 2 === 0 );
  return mod2.map( _ => _ * 2);
}
```

Proposed:
Set off, `'vars-on-top': 0`

Result:

``` javascript
function ex(a, b, c) {
  if (a) //do
  if (b) //do

  var test = [1,2,3].filter( _ => _ > 1 );
  if (test) //do

  var mod2 = test.filter( _ => _ % 2 === 0 );
  return mod2.map( _ => _ * 2);
}
```

**Comment by nzack** [comment]
Go with the bottom, where you can inline vars
