### ISSUE TITLE
brace-style

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#12]
http://eslint.org/docs/rules/brace-style
- Currently set to 1tbs. I'm a stroustrup guy and believe the extra whitespace improves readability.

``` javascript
if (x) {
  ///
} else {
  ///
}

vs

if (x) {
  ///
} 
else {
  ///
}
```

Proposed:
Use stroustrup

``` javascript
    'brace-style': [
      2,
      'stroustrup',
      { 'allowSingleLine': true }
    ],
```

**Comment by nzack** [comment]
Go with the top style.
