### ISSUE TITLE
key-spacing

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#15]
http://eslint.org/docs/rules/key-spacing
- Currently set to no space before `:` and a space after `:`, but nothing about vertical alignment

Proposed:
Discuss if we want alignment or not

Current setup

``` javascript
var data = {
  key1: 123,
  key2: 'someval',
  key3: [1, 2, 3]
}
```

Possibilities

``` javascript
var data = {
  shortKey    : 1,
  longerKey   : [1, 2, 3],
  extraLongKey: 'asd'
}

var data = {
  shortKey:     1
  longerKey:    [1, 2, 3],
  extraLongKey: 'asd'
}
```

**Comment by nzack** [comment]
Use the current setup.
