### ISSUE TITLE
spaced-comment

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#16]
http://eslint.org/docs/rules/spaced-comment
- Currently lacks support for /****\* and is only a warning

Current:

``` javascript
/**
* JSDoc
*/

/*----------
* JSDoc
*/

// Some other comment
```

Proposed:

``` javascript
'spaced-comment': [1, 'always',  {
      'exceptions': ['*'],
      'markers': ['@TODO:', '@NOTE:']
    }],
```

I use `//@TODO:` and `//@NOTE:` as a sort of tagging system. Could add in other ones like `@HACK`, `@FIXME`, etc.

All of the below should have no warning

``` javascript
/**
* JSDoc
*/

/*************
* JSDoc
*/

//@TODO: Make better comment

// Some other comment
```

**Comment by ravenac95** [comment]
does this not enforce 

```
/**
 * some thing (notice the space on the left)
 */
```

I dislike that there is no space on the left (of the asterisk)

**Comment by nzack** [comment]
Vote on this is to keep the config as is.  @Akkuma, please make it so.\

General rule is that the astericks in code blocks must be all aligned
