### ISSUE TITLE
No padded-blocks

### ISSUE THREAD

**Issue by nzack** [virtru/lint-trap#21]
I'd like to relax this restriction.  At times it's much more readable to allow an extra line to separate nested code blocks.  This rule prevents that.

**Comment by payaaam** [comment]
yes please.

**Comment by JasonGhent** [comment]
Disagree, but not strongly enough to care about tossing the rule.

**Comment by nzack** [comment]
No response for a while.. I'm going to commit the change.

**Comment by biscoe916** [comment]
I'm with Jason, but go ahead if it's causing you pain. This one is minor.
