### ISSUE TITLE
consistent-return

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#29]
http://eslint.org/docs/rules/consistent-return

**Proposal**
Add in `{treatUndefinedAsUnspecified: true}`

**Reason**
Shortcutting functions becomes very annoying when it tries to force you to specify a return type, creating additional visual noise.

**Comment by jwvirtru** [comment]
This is set: https://github.com/virtru/lint-trap/blob/master/lib/defaults.js#L102
