### ISSUE TITLE
comma-dangle

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#30]
http://eslint.org/docs/rules/comma-dangle

**Proposal**
Turn to error (2) and use only-multiline

**Alternative**
Turn to error (2) and use always-multiline

**Reason**
We had this set to 1 and wanted to support both trailing and non-trailing comma. This supports both while be strict about when we use it. The alternative would always require trailing commas, which makes diffs a little nicer too.

**Comment by jwvirtru** [comment]
This is set: https://github.com/virtru/lint-trap/blob/master/lib/defaults.js#L76
