### ISSUE TITLE
valid-jsdoc

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#31]
http://eslint.org/docs/rules/valid-jsdoc

**Propasal**
Add a requirement for JSDoc to be valid w/`{requireReturn: false}`. This also will require a param for every parameter and a return for any function that returns

**Reason**
If we are going to use JSDoc it might as well be correct and useful

**Comment by jwvirtru** [comment]
This is set: https://github.com/virtru/lint-trap/blob/master/lib/defaults.js#L97
