### ISSUE TITLE
max-statements

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#32]
http://eslint.org/docs/rules/max-statements

**Proposal**
Warn if we hit over 30 statements

**Reason**
Larger functions are harder to reason about and can't fit neatly all on the screen at once. Additionally, functions that are too large will not even be optimized.

**Comment by nzack** [comment]
+1 +1 +1 +1 love this

**Comment by jwvirtru** [comment]
This is set: https://github.com/virtru/lint-trap/blob/master/lib/defaults.js#L173
