### ISSUE TITLE
object-curly-spacing

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#33]
http://eslint.org/docs/rules/object-curly-spacing

**Proposal**
Turn to warn with always being preferred, but not enforced

**Reason**
I believe simple objects `{x: 1}` and imports don't  need it, but a one liner with a nested object spacing should be preferred.

**Comment by jwvirtru** [comment]
This is set to warn: https://github.com/virtru/lint-trap/blob/master/lib/defaults.js#L183
