### ISSUE TITLE
no-cond-assign

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#4]
http://eslint.org/docs/rules/no-cond-assign 
- Can’t use while (val = val.next()), but does prevent if (x = 1). They chose the strictest version and also prevents while ((val = val.next())) for the times you really do want that.

Current

``` javascript
while (val) {
  //do stuff
  val = val.next();
}
```

Proposed:

``` javascript
'no-cond-assign': [2, 'except-parens']
```

Result

``` javascript
while ((val = val.next()) {
  //do stuff
}
```

**Comment by nzack** [comment]
Developer preference.
