### ISSUE TITLE
no-param-reassign

### ISSUE THREAD

**Issue by Akkuma** [virtru/lint-trap#9]
http://eslint.org/docs/rules/no-param-reassign 
- Currently an error. I don't believe anyone in their right mind would access `arguments` when they have a parameter with the value already to use. I can't recall a time that this was unintended and indicative of a mistake or error.

Current

``` javascript
function ex(a, b, c) {
  var aVal = a || 'default';
  var bVal = b || 1;
  var cVal = c || 2;
}
```

Proposed:
Set off or warning

Result

``` javascript
function ex(a, b, c) {
  a = a || 'default';
  b = b || 1;
  c = c || 2;
}
```

**Comment by nzack** [comment]
Allow reassignment of varibales
